version: '3.8'
services:

  web:
    build: .
    container_name: dev-app
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./:/app
    env_file:
      - .env
    command: ["./start.sh"] 